import os
import pickle
import numpy as np
import cv2
import pytesseract
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from flask import Flask, render_template, request, send_file
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

app = Flask(__name__)

# ---------------- LOAD MODEL ----------------
model = pickle.load(open("models/heart_model.pkl", "rb"))
scaler = pickle.load(open("models/scaler.pkl", "rb"))

# ---------------- UTILITIES ----------------
def preprocess_image(image_path):
    img = cv2.imread(image_path)
    img = cv2.resize(img, (800, 800))  # prevent memory crash
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    return pytesseract.image_to_string(gray)

def generate_graph(result):
    plt.figure(figsize=(4, 4))
    plt.bar(["Prediction"], [result], color="red" if result == 1 else "green")
    plt.title("Heart Disease Prediction")
    plt.savefig("static/result_graph.png")
    plt.close()

def generate_pdf(result):
    pdf_path = "static/report.pdf"
    c = canvas.Canvas(pdf_path, pagesize=A4)
    c.drawString(100, 750, "Heart Disease Prediction Report")
    c.drawString(100, 720, f"Result: {'Disease Detected' if result == 1 else 'No Disease'}")
    c.drawString(100, 690, "Generated by ML System")
    c.save()
    return pdf_path

# ---------------- ROUTES ----------------
@app.route("/")
def index():
    return render_template("index.html")

@app.route("/predict", methods=["POST"])
def predict():
    try:
        # ---------- MANUAL INPUT ----------
        if "age" in request.form:
            features = [
                float(request.form["age"]),
                float(request.form["sex"]),
                float(request.form["cp"]),
                float(request.form["trestbps"]),
                float(request.form["chol"]),
                float(request.form["fbs"]),
                float(request.form["restecg"]),
                float(request.form["thalach"]),
                float(request.form["exang"]),
                float(request.form["oldpeak"]),
                float(request.form["slope"]),
                float(request.form["ca"]),
                float(request.form["thal"]),
            ]

        # ---------- IMAGE INPUT ----------
        else:
            file = request.files["report"]
            path = "static/upload.png"
            file.save(path)
            text = preprocess_image(path)

            # fallback values (safe defaults)
            features = [55, 1, 2, 130, 250, 0, 1, 150, 0, 1.5, 1, 0, 2]

        X = scaler.transform([features])
        result = int(model.predict(X)[0])

        generate_graph(result)
        generate_pdf(result)

        return render_template("result.html", prediction=result)

    except Exception as e:
        return f"Error occurred: {str(e)}"

@app.route("/download")
def download():
    return send_file("static/report.pdf", as_attachment=True)

# ---------------- MAIN ----------------
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8000))
    app.run(host="0.0.0.0", port=port)
